name: Release Drafter

on:
  push:
    schedule:
    - cron: '0 21 * * *'
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.DRAFTER_TOKEN }}